klass = Klass.create!(name: 'ProjectManagement::Project::Task', label: 'Project Task')
group = Group.create!(name: 'Task Information', label: 'Task Information', klass: klass, position: 1, default: true)

Field.create!(name: 'title', label: 'Task Title', column_type: 'Text', klass: klass, position: 1, placeholder: 'Task Title', min_length: nil, max_length: nil, default_value: nil, required: true, quick_create: true, key_field_view: false, mass_edit: false, deletable: false, system_field: true, group: group, custom: false, reference: false, reference_klass: nil, reference_key: nil, have_custom_value: false)
Field.create!(name: 'priority', label: 'Priority', column_type: 'Picklist', klass: klass, position: 2, placeholder: 'Task Priority', min_length: nil, max_length: nil, default_value: nil, required: true, quick_create: true, key_field_view: false, mass_edit: false, deletable: false, system_field: true, group: group, custom: false, reference: false, reference_klass: nil, reference_key: nil, have_custom_value: true)
Field.create!(name: 'status', label: 'Status', column_type: 'Picklist', klass: klass, position: 3, placeholder: 'Task Status', min_length: nil, max_length: nil, default_value: nil, required: true, quick_create: true, key_field_view: false, mass_edit: false, deletable: false, system_field: true, group: group, custom: false, reference: false, reference_klass: nil, reference_key: nil, have_custom_value: true)
Field.create!(name: 'start_date', label: 'Start Date', column_type: 'Date', klass: klass, position: 4, placeholder: 'Start Date', min_length: nil, max_length: nil, default_value: nil, required: true, quick_create: true, key_field_view: false, mass_edit: false, deletable: false, system_field: true, group: group, custom: false, reference: false, reference_klass: nil, reference_key: nil, have_custom_value: false)
Field.create!(name: 'due_date', label: 'Due Date', column_type: 'Date', klass: klass, position: 5, placeholder: 'Due Date', min_length: nil, max_length: nil, default_value: nil, required: false, quick_create: true, key_field_view: false, mass_edit: false, deletable: false, system_field: true, group: group, custom: false, reference: false, reference_klass: nil, reference_key: nil, have_custom_value: false)
Field.create!(name: 'description', label: 'Description', column_type: 'Text Area HTML', klass: klass, position: 6, placeholder: 'Project Name', min_length: nil, max_length: nil, default_value: nil, required: false, quick_create: true, key_field_view: false, mass_edit: false, deletable: false, system_field: true, group: group, custom: false, reference: false, reference_klass: nil, reference_key: nil, have_custom_value: false)

Field.create!(name: 'assigned_to_id', label: 'Assigned To', column_type: 'Picklist', klass: klass, position: 7, placeholder: 'Assigned To', min_length: nil, max_length: nil, default_value: nil, required: false, quick_create: true, key_field_view: false, mass_edit: false, deletable: false, system_field: true, group: group, custom: false, reference: true, reference_klass: 'User', reference_key: 'fullname', have_custom_value: false)
