klass = Klass.create!(name: 'ProjectManagement::Project', label: 'Project')
group = Group.create!(name: 'Project Information', label: 'Project Information', klass: klass, position: 1, default: true)

Field.create!(name: 'name', label: 'Project Name', column_type: 'Text', klass: klass, position: 1, placeholder: 'Project Name', min_length: nil, max_length: nil, default_value: nil, required: true, quick_create: true, key_field_view: false, mass_edit: false, deletable: false, system_field: true, group: group, custom: false, reference: false, reference_klass: nil, reference_key: nil, have_custom_value: false)
Field.create!(name: 'status', label: 'Project Status', column_type: 'Picklist', klass: klass, position: 2, placeholder: 'Project Status', min_length: nil, max_length: nil, default_value: nil, required: true, quick_create: true, key_field_view: false, mass_edit: false, deletable: false, system_field: true, group: group, custom: false, reference: false, reference_klass: nil, reference_key: nil, have_custom_value: true)
Field.create!(name: 'start_date', label: 'Start Date', column_type: 'Date', klass: klass, position: 3, placeholder: 'Start Date', min_length: nil, max_length: nil, default_value: nil, required: true, quick_create: true, key_field_view: false, mass_edit: false, deletable: false, system_field: true, group: group, custom: false, reference: false, reference_klass: nil, reference_key: nil, have_custom_value: false)
Field.create!(name: 'end_date', label: 'End Date', column_type: 'Date', klass: klass, position: 4, placeholder: 'End Date', min_length: nil, max_length: nil, default_value: nil, required: false, quick_create: true, key_field_view: false, mass_edit: false, deletable: false, system_field: true, group: group, custom: false, reference: false, reference_klass: nil, reference_key: nil, have_custom_value: false)
Field.create!(name: 'description', label: 'Description', column_type: 'Text Area HTML', klass: klass, position: 5, placeholder: 'Project Name', min_length: nil, max_length: nil, default_value: nil, required: false, quick_create: true, key_field_view: false, mass_edit: false, deletable: false, system_field: true, group: group, custom: false, reference: false, reference_klass: nil, reference_key: nil, have_custom_value: false)
Field.create!(name: 'client_id', label: 'Client Company', column_type: 'Picklist', klass: klass, position: 6, placeholder: 'Client Company Name', min_length: nil, max_length: nil, default_value: nil, required: true, quick_create: true, key_field_view: false, mass_edit: false, deletable: false, system_field: true, group: group, custom: false, reference: true, reference_klass: 'Client', reference_key: 'company_name', have_custom_value: false)
