### Fields For Users ###
klass = Klass.find_by(name: "User")
user_default = Group.find_or_create_by(name: "default_group", label: "User Details", klass: klass, position: "1", hint: "", default: true)
Field.find_or_create_by(name: 'first_name', label: "First Name", column_type: 'Text', klass: klass, position: 1, head_position: 1, placeholder: "First Name", min_length: 0, max_length: 255, default_value: "", required: false, quick_create: true, key_field_view: true, header_view: true, mass_edit: true, custom: false, deletable: false )
Field.find_or_create_by(name: 'last_name', label: "Last Name", column_type: 'Text', klass: klass, position: 2, head_position: 2, placeholder: "Last Name", min_length: 0, max_length: 255, default_value: "", required: false, quick_create: true, key_field_view: true, header_view: true, mass_edit: true, custom: false, deletable: false )
Field.find_or_create_by(name: 'email', label: "Email", column_type: 'Email', klass: klass, position: 3, head_position: 3, placeholder: "Email", min_length: 0, max_length: 255, default_value: "", required: true, quick_create: true, key_field_view: true, header_view: true, mass_edit: true, custom: false, group: user_default, deletable: false )
Field.find_or_create_by(name: 'password', label: "Password", column_type: 'Password', klass: klass, position: 4, head_position: 4, placeholder: "Password", min_length: 0, max_length: 255, default_value: "", required: false, quick_create: true, key_field_view: true, header_view: true, mass_edit: true, custom: false, deletable: false )
Field.find_or_create_by(name: 'password_confirmation', label: "Confirm Password", column_type: 'Password', klass: klass, position: 5, head_position: 5, placeholder: "Confirm Password", min_length: 0, max_length: 255, default_value: "", required: false, quick_create: true, key_field_view: true, header_view: true, mass_edit: true, custom: false, deletable: false )
Field.find_or_create_by(name: 'role_ids', label: 'Select Role', column_type: 'Picklist', klass: klass, position: 6, head_position: 6, placeholder: 'Select Role', required: true, quick_create: true, key_field_view: true, header_view: true, mass_edit: true, custom: false, group: user_default, deletable: false )
#Field.find_or_create_by(name: 'client_ids', label: 'Select Client', column_type: 'Picklist', klass: klass, position: 7, head_position: 7, placeholder: 'Select Client', required: true, quick_create: true, key_field_view: true, header_view: true, mass_edit: true, custom: false, group: user_default, deletable: false )
### Fields For Users ###
