klass = Klass.find_by(name: 'Invoice')
invoice_default = Group.find_or_create_by(name: "default_group", label: "Invoice Details", klass: klass, position: "1", hint: "", default: true)

Field.find_or_create_by(name: 'invoice_no', label: 'Invoice no.', column_type: 'Text', klass: klass, position: 1, placeholder: 'Invoice number', min_length: 0, max_length: 255, default_value: '', required: true, quick_create: true, key_field_view: true, header_view: true, mass_edit: false, custom: false,deletable: false)
Field.find_or_create_by(name: 'status', label: 'Status', column_type: 'Text', klass: klass, position: 2, placeholder: 'Status', min_length: 0, max_length: 255, default_value: '', required: true, quick_create: true, key_field_view: true, header_view: true, mass_edit: false, custom: false)
Field.find_or_create_by(name: 'client_id', label: 'Company Details', column_type: 'Text', klass: klass, position: 3, head_position: 1, placeholder: 'Client', min_length: 0, max_length: 255, default_value: '', required: true, quick_create: true, key_field_view: true, header_view: true, mass_edit: false, custom: false, group: invoice_default,deletable: false)
Field.find_or_create_by(name: 'invoice_date', label: 'Invoice date', column_type: 'Date', klass: klass, position: 5, head_position: 3, placeholder: 'Invoice date', min_length: 0, max_length: 255, default_value: '', required: true, quick_create: true, key_field_view: true, header_view: true, mass_edit: false, custom: false, group: invoice_default,deletable: false)
Field.find_or_create_by(name: 'due_date', label: 'Due date', column_type: 'Date', klass: klass, position: 6, head_position: 4, placeholder: 'Due date', min_length: 0, max_length: 255, default_value: '', required: true, quick_create: true, key_field_view: true, header_view: true, mass_edit: false, custom: false, group: invoice_default,deletable: false)
Field.find_or_create_by(name: 'sales_person_id', label: 'Sales person', column_type: 'Picklist', klass: klass, position: 7, placeholder: 'Select salesperson', min_length: 0, max_length: 255, default_value: '', required: true, quick_create: true, key_field_view: true, header_view: false, mass_edit: false, custom: false)
Field.find_or_create_by(name: 'total', label: 'Total', column_type: 'Text', klass: klass, position: 8, placeholder: 'Total', min_length: 0, max_length: 255, default_value: '', required: true, quick_create: true, key_field_view: true, header_view: true, mass_edit: false, custom: false)

field = Field.find_or_create_by(name: 'terms', label: "Terms", column_type: 'Picklist', klass: klass, position: 4, head_position: 2, placeholder: "Status", min_length: 0, max_length: 255, default_value: "",  required: true, quick_create: true, key_field_view: true, header_view: true, mass_edit: false, custom: false,  group: invoice_default, have_custom_value: true, system_field: true,deletable: false )
[:net_30, :net_15].each_with_index do |s, ind|
  field.field_picklist_values.find_or_create_by(value: s.to_s.humanize, position: ind+1)
end

Field.find_or_create_by(name: 'msg_on_invoice', label: 'Message On Invoice', column_type: 'Text', klass: klass, position: 9, head_position: 5, placeholder: 'Message On Invoice', min_length: 0, max_length: 255, default_value: '', required: true, quick_create: true, key_field_view: true, header_view: true, mass_edit: false, custom: false, group: invoice_default,deletable: false)
Field.find_or_create_by(name: 'msg_on_statement', label: 'Message On Statement', column_type: 'Text', klass: klass, position: 10, head_position: 6, placeholder: 'Message On Statement', min_length: 0, max_length: 255, default_value: '', required: true, quick_create: true, key_field_view: true, header_view: true, mass_edit: false, custom: false, group: invoice_default,deletable: false)
Field.find_or_create_by(name: 'attachment', label: 'Attachment', column_type: 'File', klass: klass, position: 11, placeholder: 'Attachment', min_length: 0, max_length: 255, required: false, quick_create: true, key_field_view: true, header_view: false, mass_edit: false, custom: false, group: invoice_default,deletable: false)
